### ISSUE TITLE
Events Calendar

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#10]
Hello, I have an [events](https://intranet.1.jccmi.edu/events/) page. Can we add the calendar like we have on the main site as well as pull in a list of upcoming events to the [dashboard](https://intranet.1.jccmi.edu/home/) page?

**Comment by d4mation** [comment]
I noticed that https://intranet.1.jccmi.edu/home/ is not set as your Home Page. It is also set up in a way is different than https://intranet.1.jccmi.edu/, which is your actual Home Page.

Would you want to break out the Announcements and Events listing from https://intranet.1.jccmi.edu/home/ into shortcodes so that they can be used for this Issue and #9? Then we could make https://intranet.1.jccmi.edu/home/ and it could keep the same layout that it has now.

**Comment by banksashleym** [comment]
Yes, I tried to set /home as the static home page, but then I wasn't able to edit any of the content on that page, it was just a list of the blog posts and events listing. I would like to set up the /home as the main dashboard page and have it keep that same styling.

Also, I downloaded a plugin (content views) to start playing around with adding recent posts to that home page as well as being able to pull out tagged announcements and add them to our department pages. I know you guys are so busy and I wasn't sure if this was a better solution so you didn't have to do any custom coding?

**Comment by d4mation** [comment]
> I know you guys are so busy and I wasn't sure if this was a better solution so you didn't have to do any custom coding?

Generally, I'd say _no_ to this. Not because it is a bad idea overall, but it makes it so that if in the future you want to do something that this plugin does not support we then have to "support" using this 3rd party plugin. It can make it harder for us to include any custom functionality for you within these templates/layouts that the plugin creates.

I have made the Blog Posts into a Shortcode called `[jc_intranet_blog]` where you can define a `category` Attribute in order to show results only from a certain Category. So you could do something like `[jc_intranet_blog category="Department"]`.

I have also made the Events into a Shortcode called `[jc_intranet_events]` which will pull in the Events in a list.

These are laid out in the exact same way as they are currently on https://intranet.1.jccmi.edu/, which isn't a match for how you've done it with that plugin. Is the left column with 1 Post and the right column with 3 Posts the look that you're going for?

I have removed the hard-coded Front-Page template so that your created Home page will work as well. 

I would assume that Shortcodes can be used with the plugin you've implemented, but it may not work in that way. However, the layout that you've made with that plugin could potentially be replaced by the Shortcodes so it likely would not matter.

--- 

Note: I have not pushed these changes yet. But I wanted

**Comment by banksashleym** [comment]
Yes, I totally agree! I would much rather have you code everything. I'm always leary of adding plugins just because you never know what you're going to get. With this one, I like the functionality and flexibility in layout for different views. For instance, on the [main page](https://intranet.1.jccmi.edu/home/) I can lay the blog posts where there is the one main column and three smaller listings to the right, then on the [announcements](https://intranet.1.jccmi.edu/announcements/) page I can list them all and toggle them by category, then on each [department](https://intranet.1.jccmi.edu/departments/human-resources/) I can list by category as a collapsible list so they aren't distracting. 

I feel like I'm pushing it as far as customizing the template, but if this is something that can easily be coded on your end that would be great!

**Comment by d4mation** [comment]
If you do the following, it is now possible to replicate a similar layout to what is there currently:

```
[row]
[column sizes="small-12 medium-6"]
[jc_intranet_blog results=1 layout="single"]
[/column]
[column sizes="small-12 medium-6"]
[jc_intranet_blog results=3 offset=1]
[/column]
[/row]
```

This Issue will auto-close once I merge into `master`, but I am going to ensure I tag a new version to prevent issues with caching :+1:

**Comment by banksashleym** [comment]
Great! I can disable and remove the plugin and will start using the shortcode.

**Comment by d4mation** [comment]
I have pushed this code to Live. Should be ready to use :+1:

You should be able to change your Home Page to be the Home Page you created without any conflict now as well.

**Comment by banksashleym** [comment]
Great, thanks!!
