### ISSUE TITLE
Employee Directory

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#11]
I imported our employees into the [employee directory](https://intranet.1.jccmi.edu/employee-directory/) page. I think for the sake of time I can update in both the main site as well as the intranet until we can link the two later on down the road. Is it possible to include a search feature so that an employee can type in a name and it will filter the employees? Can you also place these in a grid maybe two or three across?

**Comment by d4mation** [comment]
Including extra functionality for a Search Feature _now_ could unfortunately make the switchover later more difficult than it needs to be, since the "built-in" Employee Directory code from jccmi.edu does not support this. 

When we had originally talked about having the Intranet site pull this data from jccmi.edu, I was going to build out any necessary additional functionality (Like search) that would be independent of the setup that was on jccmi.edu. 

I could however change the grid size most likely. I would just need to look at how it is done.

---

Note: Last week when taking care of #6 (And #14), we went over by about an hour for our weekly time allotment. We can continue to forge ahead if you'd like, but we will have to continue borrowing "future time" which would lead into a dry spell further down the line. Just wanted to give you a heads up 👍

**Comment by banksashleym** [comment]
No worries! We can include the search later when we integrate the intranet directory with the main site. There is the ability with shortcode currently to do display="grid" but then it removes the A-Z selection at the top and I think people find that helpful. If this is going to be a hassle then we can incorporate the grid at a later date as well.

**Comment by banksashleym** [comment]
And it's ok if we borrow time, we would love to get this up and running ASAP. If you could just let me know when we can pick back up on the weekly issues after this project that would be great.

**Comment by d4mation** [comment]
Alrighty, I'll let you know when we can pick up on the weekly issues. :+1:

I'll see what I can do about the A-Z, Searching, and Grid Sizing.

**Comment by d4mation** [comment]
I just pushed this change to Live. It only applies when the Shortcode is set to `display="grid"`, but it gives you the 3-per row, the letters that you can click on to skip ahead, and the ability to Search. 👍

**Comment by banksashleym** [comment]
I love it!! Thanks so much!
