### ISSUE TITLE
Header Image in Template

### ISSUE THREAD

**Issue by d4mation** [JacksonCollege/jc-intranet-theme#14]
From #6 

> Also, can we add a spot that we can add a header/feature image that would span across all pages? I'm thinking the logo/header area doesn't have to be any taller than 175 px. See the image below (I've already done some styling to the left navigation) 
> ![image](https://user-images.githubusercontent.com/7770631/56057478-e5642300-5d2c-11e9-8637-dcbff0f2ca45.png)

@banksashleym Is the idea that all pages (Posts, Pages, etc.) should have the option for a banner image like this? Is the banner image the same across all pages?

I got focused on the logo aspect of #6 and did not realize that Issue was for two things.

**Comment by banksashleym** [comment]
Sorry, I should have made this two issues. Yes, I would like to have a spot to upload one image and have it span across all pages/posts, etc..I just added [this issue](https://github.com/JacksonCollege/jc-intranet-theme/issues/13) because when I upload a feature image to the blog posts it's putting it in that top narrow spot. If he had a consistent photo across all pages/posts, then on the post pages where there is a featured image if we could move that down into the body of the content that would be great.

**Comment by d4mation** [comment]
I've pushed a change for this. You can find the option to set the Global Banner in the same place as the Logo. :+1:

**Comment by d4mation** [comment]
A minor note regarding this: I disabled the "Front" Page Template since the "Front" Page Template was including its own version of a Banner Image and the only way I could get rid of it was to override the Template itself. But if I were to override the "Front" Page Template to remove its special Banner Image, then it would have been no different than the "Default" Page Template anyway. 

It seems that you were not using it on the Intranet anyway, but I wanted to make sure to mention it.

**Comment by banksashleym** [comment]
Perfect, thank you!
