### ISSUE TITLE
footer stick to the bottom

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#20]
I tried styling the footer but I'm going around in circles! For the footer can we just make it a fixed height (50px should be fine, color #000) that sticks to the bottom? For instance on our business office page it looks weird with a tall footer since there isn't much content. Thank you!

**Comment by d4mation** [comment]
By color, do you mean background color or text color? Just making sure since `color` in CSS refers to text color.

**Comment by banksashleym** [comment]
Sorry, yes background color

**Comment by d4mation** [comment]
Just pushed this change up :+1:

**Comment by banksashleym** [comment]
Thanks! Sorry, I think I may have meant the wrong thing :) Can we have this footer show up at the bottom after all of the content? So like our main site where even if the page is really long you won't see the footer until you scroll down to the very bottom.

**Comment by d4mation** [comment]
Is there a short page like the Intranet Business Office page on jccmi.edu? 

I have made it so that the Footer is not stuck at the bottom of the screen all the time but rather stuck at the bottom of the content on my local environment and it ends up looking like this:

![image](https://user-images.githubusercontent.com/7770631/57086805-d12c9980-6ccc-11e9-84cd-3c296ec41b30.png)

I figure the space below the footer is not wanted, so I want to know if there is an example of a similar situation on jccmi.edu that I can look at.

**Comment by banksashleym** [comment]
I created a [test page](https://www.jccmi.edu/test-page/) on jccmi.edu where there is just a little content and I guess the footer does jump up here as well...I don't necessarily think we even need a footer? Is a footer section required? I wouldn't mind if we just eliminated it altogether and had the light gray/white area just run off the page (see below). And if that is going to be too complicated we can even just make the black footer bar match the light gray surrounding the white main content area. Thanks!
![Capture](https://user-images.githubusercontent.com/15264315/57088135-a1cb5c00-6ccf-11e9-9d9a-a2b57409ff22.JPG)

**Comment by banksashleym** [comment]
I would ideally love it to look like below. Where on short pages the white area would just expand until you get to the footer at the bottom. Sorry so confusing!
![Capture2](https://user-images.githubusercontent.com/15264315/57088341-18685980-6cd0-11e9-9ae0-9612a80113d5.jpg)

**Comment by d4mation** [comment]
The issue with expanding the main content area (The white area) to the full height in situations like the Business Office page (Where it doesn't do so naturally) is that I would need to calculate that height. While the footer is not in use now, if it were to be in use in the future by things like Menus, copyright text, etc. I could no longer calculate this height.

I have removed the Footer since, like you said, it is not in use currently. This allowed me to extend the main content area to reach the bottom of the screen regardless of the height of the actual content on the page. These changes are now Live.

The only way we could have the footer be included while extending the main content area to always fill the screen would be:

1. Calculate the height of the footer using JavaScript after the page loads so that we do the calculations necessary on-the-fly. This would mean things "jumping" into place on page load which can be distracting.
2. Instead of making the main content area extend to the height of the screen, we would have the footer extend upward to meet the main content area. On short pages like the Business Office, this could look pretty bad.

What do you think?

**Comment by banksashleym** [comment]
I think this is perfect with the footer removed altogether. Thank you!
