### ISSUE TITLE
Give employees access to change their employee picture/name

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#24]
Hello! We launched the intranet last week and it has gotten really great feedback - thanks for all of your work!

I've noticed that depending on how an employee logs in it will use that as their username for the message boards. For instance, if the log into the adfs using just the first par of their username (without the @jccmi.edu so when I logged in as banksashleym) it pulls their name from the employee directory and displays my name "Ashley Banks". But if they login with their username (banksashleym@jccmi.edu) it will pull banksashleym@jccmi.edu instead of "Ashley Banks". 

Anyway, I've been going in on the back end and if I notice that they initially log in with their username I will manually enter their name. Another thing I noticed is that we have a lot of adjuct faculty who aren't in our employee directory so it has just a default picture for them.

So to get to the point (LOL) could we enable back that black toolbar so a user can get into their profile and edit their display name and have the ability to upload a profile image?

**Comment by d4mation** [comment]
I just pushed changes for the above :+1:

It turns out Subscribers were being granted the `edit_posts` capability for one reason or another. I have adjusted the check to hide the Admin Bar to be based directly on their role rather than their Capability. I have also adjusted the bbPress Frontend User Edit screen to remove the unneeded fields.

Let me know what you think!

**Comment by banksashleym** [comment]
This is awesome!! Thank you!

**Comment by banksashleym** [comment]
This is awesome, thank you!!

**Comment by d4mation** [comment]
GitHub is being really screwy on my end (showing comments as being from the future) and not showing all comments properly, but I saw the email notification which says that this is all good so I'm going to close this issue. If something comes up or if I missed something due to GitHub being glitchy, feel free to re-open :+1:

**Comment by banksashleym** [comment]
Yes, I just noticed that! My comments weren't showing up and then they popped up in the middle of the thread :) This is good to be closed. Thank you!
