### ISSUE TITLE
Intranet login directing to Wordpress login instead of adfs

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#25]
Hello, I'm getting questions from employees that they are not able to login anymore to the intranet? When they click on intranet.1.jccmi.edu it's directing them to the wordpress login page instead of the adfs login? I was wondering if you could look at that this morning if you have time? We send out a weekly email every monday morning with the news for the week. Thanks!

**Comment by d4mation** [comment]
Looking here, it seems the SAML plugin disabled itself because you added another Sub-Site to the Network?

There's no real reason that it should have done this, since you only had it in-use on the Intranet Subsite. It was turned off for all the other ones.

It looks like the developers will need contacted to figure out why this is going on. It really shouldn't be checking for the number of Sub-Sites that exist but rather how many of them are using it for log-in. 

https://www.jccmi.edu/wp-admin/network/admin.php?page=mo_saml_settings&tab=login

**Comment by banksashleym** [comment]
Thanks so much for checking this out! I deleted the subsite I created for now and will get with the developers of the plugin. Yes, I believe we enabled the plugin to only use sso for the intranet so that is weird. I really appreciate you looking into this on short notice. Have a great day!

**Comment by banksashleym** [comment]
Sorry, I did have one more question. After I deleted the subsite, there is a warning on the SSO login options. https://www.jccmi.edu/wp-admin/network/admin.php?page=mo_saml_settings. Is it ok to have these items checked in option 1?

**Comment by d4mation** [comment]
Yes, please leave those options checked if you would. This allows Steve and I the ability to still log in since we don't have Active Directory credentials with you guys. It allows us to get to the regular WP Login Screen to use our WordPress credentials to log in.

**Comment by banksashleym** [comment]
Sounds good, thank you!

**Comment by banksashleym** [comment]
I have contacted the developer of the SSO plugin and here is their response:

> You are currently using the multi-site version of miniOrange SAML SP SSO plugin. 
> This plugin works with the number of subsites for which you have paid while purchasing the plugin. The minimum bracket for this is 3 subsites, which is selected by default while purchasing the plugin. 
> This is the reason you are not able to use the plugin after adding a 4th subsite. 
> 
> Even though you are using SSO only on a single subsite, the plugin takes into consideration all the subsites available in the WordPress multisite environment. 
> This is to support the generic multisite use case where the admin can control user creation throughout the multisite network and manipulate subsite specific attributes and roles for each user. 
> 
> If you plan to use SSO only in one particular subsite, you could have gone for the single site SAML SSO plugin instead and install it on the particular subsite where you want to use it. 
> However, please note that, in this case the users will only be created in that subsite only and thus they won't be able to freely access the other subsites.
> 

Would there be a case where we would need the users to freely access the other subsites? Do you think the best plan of action would be to see if they could switch this to the single site SAML SSO? Let me know your thoughts. Thanks!

**Comment by d4mation** [comment]
> However, please note that, in this case the users will only be created in that subsite only and thus they won't be able to freely access the other subsites.

I think they're a little confused here in how Users work in a WordPress Multisite. 

In a WordPress Multisite, whenever you add a new User to a Sub-Site it creates a "Global" user for them no matter what. They just won't be "added" to the other Sub-Sites automatically. This is how their plugin works with the multisite configuration as well.

For instance, here's a user that was created by their plugin for the Intranet when viewed from the Network Dashboard:

![image](https://user-images.githubusercontent.com/7770631/58036396-fe64ae80-7af8-11e9-8d47-097f45fbb225.png)

As you can see, they were only added to the Intranet Sub-Site. 

Now here's an example from one of our own Multisites (That isn't using a special plugin like theirs) where a User was created for a specific Sub-Site:

![image](https://user-images.githubusercontent.com/7770631/58036590-7337e880-7af9-11e9-81ca-c8c2e8a209d8.png)

No matter how a User is created in a WordPress Multisite, they are added to a global `wp_users` Database Table and from there they are "mapped" to specific Sub-Sites. 

So for their example where "users will only be created in that subsite only and **thus they won't be able to freely access the other subsites.**" is actually not really true. If you log in as a User that was made for a specific Sub-Site but then navigate to another Sub-Site on that Multisite (Including the primary one) they will stay logged in, but they won't have any privileges, which is to be expected. 

My guess as to what they mean by that would be that you could technically assign them to multiple sites at once using their plugin on login instead of only mapping them to the specific site that they logged into. 

---

If you only care to have Single Sign-On apply to the Intranet Sub-Site, you could go with the Single-Site package like they said. We went with the Multi-Site package since it is a Multi-Site and some plugins that otherwise have "Multi-Site Support" like this one often do not work if they're activated on a single Sub-Site and will instead tell you to use the Multi-Site version or to Network Activate it. 

You will want to ensure you get the Premium Package again so that Attribute and Role Mapping are available. We'd also have to reconfigure it once activated on the individual site, which would hopefully be copy/pasting the settings. 

...They really should change the wording on "up to 3 sites" though, since it is very misleading. It should be up to 3 configured sites, not 3 Sub-Sites on your network only whether or not they're configured for this.

**Comment by banksashleym** [comment]
Wow, yes they seem a bit confused...Let me see if there is anything they can do without us having to go back to the single site. I will let you know what they say. Thanks!

**Comment by banksashleym** [comment]
Here is the response from the plugin developers:
We concluded that there could be two possible solutions for this, as I have mentioned below.

> 1.	The first and easiest solution would be to upgrade your multi-site license so that it can be used for the appropriate number of sub-sites.
> For example, if you want to add 10 more sub-sites, simply upgrade your license for 10 more sub-sites. You can do so by following this link and purchasing the license upgrade for as many sub-sites as you want.
> 
> If you go with this option, you don't need to make any changes in your existing setup and everything will continue to work as it should. In addition, you will be able to add more sub-sites as per the number of sub-sites for which you have upgraded the license.
> 2.	The second solution would be to change your existing multi-site plugin with the single site plugin.
> 
> If you want to go with this option, just let me know. We will provide you the single site plugin. You will be able to perform SSO in only one particular sub-site. You will be able to add as many sub-sites as you want without any restrictions.
> Rest assured, we will help you in setting up the plugin with your Identity Provider. For this, we can setup a screen share session with someone from your IT department and work with them to configure the plugin. 

I'm thinking that it makes more sense to switch to the single site plugin? Once I have the plugin from them, could you let me know the process to switch this over and I can get with Kelly in IT and let her know she will have to configure again? Thanks!

**Comment by banksashleym** [comment]
Good morning Eric,
I have been in contact with the Mini Orange support team about switching this SSO plugin over to the single site vs. the multi site so that I am not restricted on the amount of sub sites we can add. They have switched our licensing over and gave me these instructions:

> 1.	Click here and log in with your miniOrange account.
> 2.	Click on the Download plugin link for WordPress SAML SSO SP PLUGIN
> 3.	Go to your WordPress admin dashboard and take a backup of the existing plugin configuration(IMPORTANT), then deactivate and delete the plugin.
> 4.	After this, you can install the single site plugin that you downloaded from the above link by uploading the zip file.
> 5.	Activate the plugin on the sub-site in which you want to use it.
> 6.	Configure the plugin using the saved configuration from step 3.

I have deactivated and deleted the old plugin, downloaded and installed the new single site plugin just on the intranet subsite, and added in our IT configuration (taken from the screenshots of the last configured plugin). The test configuration worked and I was taken to the login screen when I went to intranet.1.jccmi.edu and successfully logged in. However instead of going to intranet.1.jccmi.edu it directed me to www.jccmi.edu when I logged in. So I'm thinking some of the configuration from the last plugin doesn't apply or may be different? 

If you have a few minutes today to take a look at the new configuration I would greatly appreciate it! No worries if not, the plugin support team said that I could reach out to them as well for help.

Thanks!
Here are the screenshots I took of the last configuration of the plugin:
[6.pdf](https://github.com/JacksonCollege/jc-intranet-theme/files/3257400/6.pdf)
[1.pdf](https://github.com/JacksonCollege/jc-intranet-theme/files/3257401/1.pdf)
[2.pdf](https://github.com/JacksonCollege/jc-intranet-theme/files/3257402/2.pdf)
[3.pdf](https://github.com/JacksonCollege/jc-intranet-theme/files/3257403/3.pdf)
[4.pdf](https://github.com/JacksonCollege/jc-intranet-theme/files/3257404/4.pdf)
[5.pdf](https://github.com/JacksonCollege/jc-intranet-theme/files/3257405/5.pdf)

**Comment by d4mation** [comment]
I adjusted this setting. I believe that this should work (I cannot fully test it since I do not have an Active Directory account)

![image](https://user-images.githubusercontent.com/7770631/58960967-3cf39d80-8776-11e9-9d42-bd39dad5892d.png)

I removed the links to your configuration screenshots. There is some fairly sensitive information in the configuration for this plugin (Certificates and such) and [this is a Public Repository](https://github.com/JacksonCollege/jc-theme-2015/issues/283) so I wanted to prevent that from getting into the wrong hands :+1:

**Comment by banksashleym** [comment]
Oh gosh, sorry I should know better than to do that. Bummer, It still redirects to www.jccmi.edu after I put in the login details.

**Comment by banksashleym** [comment]
Hi Eric,
I talked with Kelly in IT and she had to update the configuration and this new single site plugin is working now. I appreciate your help!
