### ISSUE TITLE
left nav disable parent link

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#8]
Sorry, me again! Is it possible to "disable" or bypass the parent link in the navigation? For instance, I don't really want to have a departments landing page, but i would like for them to be able to click on "departments" and have the drop down open up similar to how our [main site navigation](https://www.jccmi.edu/financial-aid/) works? Right now, if you click on "departments" it will take you to the departments landing page. and if you click on the arrow the sub menu will drop down. I would love to just be able to click on departments and have the the sub-menu drop down.

**Comment by d4mation** [comment]
> I don't really want to have a departments landing page

If you do not want to have an actual Page/Post to exist for a Menu Item, you can use the `Custom Links` option and I can add some code to where if a Parent item with just `#` for its URL is clicked, it will toggle Open/Closed without trying to go anywhere.

![image](https://user-images.githubusercontent.com/7770631/55479333-d8885680-55eb-11e9-8356-92e163842cab.png)

**Comment by banksashleym** [comment]
That would be perfect, thanks!

**Comment by d4mation** [comment]
I just pushed the change for this. If you need any tweaks to this, feel free to reopen the issue :+1:

**Comment by d4mation** [comment]
Did you hard-refresh your Internet browser? Clicking the Departments text itself works for me. 

This theme is at a weird stage in development where I haven't been tagging new version numbers, but it is now on a Production server so assets are being cached. 

If there are people other than you and us using it though, I'll start tagging each change that I make in order to force-clear the cache.

**Comment by banksashleym** [comment]
Yes, did a hard refresh and it's working now :) I appreciate it!
